"""Sound Hub — configuration shim.

Loads config/soundhub.conf using importlib so the config file can use a
.conf extension rather than .py, while still using plain Python assignment
syntax.  All uppercase names from soundhub.conf are exported into this
module's namespace so existing imports (from . import config) work unchanged.

Do not edit this file.  Edit config/soundhub.conf instead.
"""
import importlib.util
from importlib.machinery import SourceFileLoader
from pathlib import Path

_conf_path = Path(__file__).parents[1] / "config" / "soundhub.conf"

if not _conf_path.exists():
    raise RuntimeError(
        "\n\nconfig/soundhub.conf not found.\n"
        "Copy config/soundhub.conf.example to config/soundhub.conf and\n"
        "adjust the settings for your installation before starting Sound Hub.\n"
    )

_loader = SourceFileLoader("soundhub_conf", str(_conf_path))
_spec   = importlib.util.spec_from_loader("soundhub_conf", _loader)
_mod    = importlib.util.module_from_spec(_spec)
_loader.exec_module(_mod)

# Export all uppercase names into this module's namespace.
globals().update({k: v for k, v in vars(_mod).items() if k.isupper()})
